services:
  mysql:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}-mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default

volumes:
  mysql_data:

networks:
  default:
    external:
      name: ${NETWORK_NAME}
